# Generated by Django 3.2.6 on 2021-08-22 16:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('conference', models.CharField(max_length=3)),
                ('division', models.CharField(max_length=20)),
                ('primary_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('secondary_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('tertiary_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
        ),
    ]
